<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Cargo\" />
      <Folder Include="Orders\" />
      <Folder Include="Patterns\" />
      <Folder Include="Reporting\" />
      <Folder Include="Repositories\" />
      <Folder Include="Routes\" />
      <Folder Include="Serialization\" />
      <Folder Include="Services\" />
      <Folder Include="Vehicles\" />
    </ItemGroup>

</Project>
